### ISSUE TITLE
failure to create json example of empty objects

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-inflector#108]
A model like this:

```java
ArrayExample example = new ArrayExample();
example.add(new StringExample());
```

Will render nonsense as JSON:

```json
[ { : null
} ]
```

The primitive `StringExample` inner type should not be rendered as an object without a key.

**Comment by olensmar** [comment]
@fehugy unfortunately I still get errors for this from the XmlExampleSerializer:

```
javax.xml.stream.XMLStreamException: Trying to output non-whitespace characters outside main element tree (in prolog or epilog)
	at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1537)
	at com.ctc.wstx.sw.BaseStreamWriter.reportNwfStructure(BaseStreamWriter.java:1566)
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:403)
	at io.swagger.inflector.examples.XmlExampleSerializer.writeTo(XmlExampleSerializer.java:125)
	at io.swagger.inflector.examples.XmlExampleSerializer.writeTo(XmlExampleSerializer.java:108)
	at io.swagger.inflector.examples.XmlExampleSerializer.serialize(XmlExampleSerializer.java:40)
```
