### ISSUE TITLE
JSON Serialization error when processing model with xml name for array items

### ISSUE THREAD

**Issue by jweisman** [swagger-api/swagger-inflector#300]
When processing a JSON example for a model that has an xml name for array items, we get the following error.

```
com.fasterxml.jackson.core.JsonGenerationException: Can not write a string, expecting field name (context: Object)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1961)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._reportCantWriteValueExpectName(JsonGeneratorImpl.java:244)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._verifyPrettyValueWrite(JsonGeneratorImpl.java:234)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._verifyValueWrite(WriterBasedJsonGenerator.java:846)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeString(WriterBasedJsonGenerator.java:368)
	at io.swagger.oas.inflector.processors.JsonNodeExampleSerializer.writeValue(JsonNodeExampleSerializer.java:160)
	at io.swagger.oas.inflector.processors.JsonNodeExampleSerializer.writeTo(JsonNodeExampleSerializer.java:82)
	at io.swagger.oas.inflector.processors.JsonNodeExampleSerializer.writeValue(JsonNodeExampleSerializer.java:93)
	at io.swagger.oas.inflector.processors.JsonNodeExampleSerializer.writeTo(JsonNodeExampleSerializer.java:72)
	at io.swagger.oas.inflector.processors.JsonNodeExampleSerializer.serialize(JsonNodeExampleSerializer.java:47)
	at io.swagger.oas.inflector.processors.JsonNodeExampleSerializer.serialize(JsonNodeExampleSerializer.java:1)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:993)
	at io.swagger.util.Json.pretty(Json.java:23)
```

Here's the problematic model:
```
components:
  schemas:
    Pet:
      type: object
      properties:
        name:
          type: string
          example: doggie
        shots:
          type: array
          items:
            type: string
            example: rabies
            xml:
              name: shot
          xml:
            name: shots
            wrapped: true            
      xml:
        name: Pet
```

**Comment by gracekarina** [comment]
Closed by #301
